name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Adjust this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Navigate to the resume-app and install dependencies
    - name: Install dependencies
      run: |
        cd 1_hafta/1_3/resume-app
        npm install

    # Step 4: Build the project
    - name: Build project
      run: |
        cd 1_hafta/1_3/resume-app
        npm run build

    # Step 5: Upload to S3
    - name: Deploy to S3
      run: |
        cd 1_hafta/1_3/resume-app
        aws s3 sync ./build s3://$S3_BUCKET_NAME --region $AWS_REGION --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
